[arviz_example_data]
git-tree-sha1 = "1ea01419c2c0cd6cf2b2daffb235fc17091e30bc"

    [[arviz_example_data.download]]
    sha256 = "eae35685807a0dcbbf405b21eaf5fa7aff6729c5a33f8f800f093c5a8318aa2b"
    url = "https://github.com/arviz-devs/arviz_example_data/archive/refs/tags/v0.1.0.tar.gz"
