[arviz_example_data]
git-tree-sha1 = "1a48fb48ab2b35cdeeb84e0dcdcda134e24a1c20"

    [[arviz_example_data.download]]
    sha256 = "0b036ee9ae20aae544f087a490e369b844f5607552e445e08036244ad656de51"
    url = "https://github.com/arviz-devs/arviz_example_data/archive/refs/tags/v0.1.1.tar.gz"
