name = "ArviZExampleData"
uuid = "2f96bb34-afd9-46ae-bcd0-9b2d4372fe3c"
authors = ["Seth Axen <seth.axen@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
